// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnityDebugExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "UnityDebugExtension.06f4a7e1-7c99-4f17-b561-4c9abe4fdaf4";
        public const string Name = "Unity Debug Extension";
        public const string Description = @"Adds command to attach Unity debugger after running a script";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "olavim";
        public const string Tags = "";
    }
}
