// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnityDebugExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidUnityDebugExtensionCmdSetString = "5d244280-614e-400f-99f3-8301c151faed";
        public static Guid guidUnityDebugExtensionCmdSet = new Guid(guidUnityDebugExtensionCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int cmdidRunCmdAndAttach = 0x0100;
    }
}